export var AppKey : any = 'vtexappkey-naturalscents-NTQVND'
export var AppToken : any  = 'KRDZWGLOPYMLZINMREYOWLMMTRUFZLOBIYZQCQKUBOFTLBGKMKBTFIALXEBZQTBMUHRECWDWJXKHAUMNAAWMDXJAXBAPCVAPVFLHLBNGCNNHXRPJTBUPCYNKXLDOVHIK';
export const apiKey_google = " AIzaSyA3bsDl1xddiU_w38hA-fsGea8kWsp5uJM";